@startuml images/マスタ管理/従業員マスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/従業員マスタ
' 
hide circle
' 
hide method
' hide members
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "従業員マスタ"{
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "削除" #98fb98
    class "従業員情報" #F5A9BC
    class "店舗情報モデル"

    ' ユーザ -- 参照
    ' ユーザ -- 登録
    ' ユーザ -- 編集
    ' ユーザ -- 削除
    ' 参照 -- 従業員情報
    ' 登録 -- 従業員情報
    ' 編集 -- 従業員情報
    ' 削除 -- 従業員情報
    ' 従業員情報 -- 店舗情報モデル
    ユーザ --> 参照
    ユーザ --> 登録
    ユーザ --> 編集
    ユーザ --> 削除 : > has-one
    ユーザ --> ログイン
    参照 --o 従業員情報
    登録 --o 従業員情報
    編集 --o 従業員情報
    削除 --o 従業員情報 : > has-many
    従業員情報 o-- 店舗情報モデル
    ' 従業員情報 o-- 勤務店舗状況

    従業員情報 : 従業員ID
    従業員情報 : 店舗名
    従業員情報 : 雇用形態
    従業員情報 : 氏名
    従業員情報 : カナ氏名
    従業員情報 : 電話番号
    従業員情報 : 性別
    従業員情報 : 年齢
    従業員情報 : 生年月日

    店舗情報モデル : 店舗名

    従業員情報 : 主な店舗
    ログイン : 従業員ID
    ログイン : パスワード
    ' 勤務店舗状況 : 店舗名
    ' 勤務店舗状況 : 従業員数
    ' 勤務店舗状況 : 責任者
    ' 店舗情報モデル : 店舗名
    ' 店舗情報モデル : 住所
    ' 店舗情報モデル : 連絡先
    ' 店舗情報モデル : 店長
    ' 店舗情報モデル : 主な従業員
}






@enduml