@startuml images/マスタ管理/店舗マスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/店舗マスタ
' 
hide circle
' 
hide method
' hide members
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
    }

package "店舗マスタ"{
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    class "店舗情報モデル" #F5A9BC
    class "従業員情報モデル"
    class "取置商品モデル"
    class "セット商品モデル"
    ' class "" #F5A9BC
    ' class "" #F5A9BC
    

    ユーザ --> 参照
    ユーザ --> 登録
    ユーザ --> 編集
    ユーザ --> 詳細
    ユーザ --> ログイン
    参照 --o 店舗情報モデル
    登録 --o 店舗情報モデル
    編集 --o 店舗情報モデル
    詳細 --o 店舗情報モデル : > has-many
    店舗情報モデル o-- 勤務店舗状況
    店舗情報モデル o-- 従業員情報モデル
    店舗情報モデル o-- 取置商品モデル
    店舗情報モデル o-- セット商品モデル

    店舗情報モデル : 従業員ID
    店舗情報モデル : 場所カテゴリ
    店舗情報モデル : 店舗名
    店舗情報モデル : 住所
    店舗情報モデル : 連絡先
    店舗情報モデル : 無効フラグ
    店舗情報モデル : 作成日時
    店舗情報モデル : 最終更新
    ' 勤務店舗状況 : 店舗名
    ' 勤務店舗状況 : 従業員数
    ' 勤務店舗状況 : 責任者
    ' 店舗情報モデル : 店舗名
    ' 店舗情報モデル : 住所
    ' 店舗情報モデル : 連絡先
    ' 店舗情報モデル : 店長
    ' 店舗情報モデル : 主な従業員
    ' セット商品モデル : セット商品ID
    ' セット商品モデル : セット名
    ' セット商品モデル : 商品コード
    ' セット商品モデル : 型番
    ' セット商品モデル : 店舗ID[FK]
    ' セット商品モデル : 商品数
    ' セット商品モデル : 作成日時
    ' セット商品モデル : 最終更新日時
    ' 取置商品モデル : 取置予約ID
    ' 取置商品モデル : 商品コード[FK]
    ' 取置商品モデル : 型番
    ' 取置商品モデル : 店舗ID[FK]
    ' 取置商品モデル : 予約者氏名
    ' 取置商品モデル : 連絡先
    ' 取置商品モデル : 予約日時
    ' 取置商品モデル : 最終更新日時
    ' 従業員情報モデル : 従業員ID
    ' 従業員情報モデル : 雇用形態
    ' 従業員情報モデル : 店舗ID[FK]
    ' 従業員情報モデル : 氏名
    ' 従業員情報モデル : 氏名(カナ)
    ' 従業員情報モデル : 電話番号
    ' 従業員情報モデル : 性別
    ' 従業員情報モデル : 生年月日
    ' 従業員情報モデル : 年齢
    ' 従業員情報モデル : パスワード
    ' 従業員情報モデル : 無効フラグ
    ' 従業員情報モデル : 作成日時
    ' 従業員情報モデル : 最終更新日時
    ログイン : 従業員ID
    ログイン : パスワード
}


@enduml