@startuml images/マスタ管理/商品マスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/商品マスタ
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "商品マスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    ' メインのモデルは赤
    class "商品情報モデル" #F5A9BC 
    class "カテゴリモデル" 
    package "ベンチマークマスタ"{
        class "GPUベンチマークモデル"
        class "CPUベンチマークモデル"
    }
    class "店舗情報モデル"
    class "売上情報モデル" 
    class "セット商品モデル"
    class "セット商品中間モデル"
    class "取置商品モデル"












    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 登録
    ユーザ -- 編集
    ユーザ -- 詳細
    参照 -- 商品情報モデル
    登録 -- 商品情報モデル 
    編集 -- 商品情報モデル 
    詳細 -- 商品情報モデル
    商品情報モデル -- カテゴリモデル
    商品情報モデル -- 売上情報モデル
    商品情報モデル -- 店舗情報モデル
    商品情報モデル -- ベンチマークマスタ
    商品情報モデル -- 取置商品モデル
    商品情報モデル -- セット商品中間モデル
    商品情報モデル -- セット商品モデル
    'ドメインクラスの属性
    ' カテゴリモデル : カテゴリID
    ' カテゴリモデル : カテゴリ名
    ' 取置商品モデル : 取置予約ID
    ' 取置商品モデル : 商品コード[FK]
    ' 取置商品モデル : 型番
    ' 取置商品モデル : 店舗ID[FK]
    ' 取置商品モデル : 予約者氏名
    ' 取置商品モデル : 連絡先
    ' 取置商品モデル : 予約日時
    ' 取置商品モデル : 最終更新日時
    ' セット商品中間モデル : セット中間ID
    ' セット商品中間モデル : セット商品ID[FK]
    ' セット商品中間モデル : 商品コード[FK]
    ' セット商品中間モデル : 販売価格
    ' セット商品モデル : セット商品ID
    ' セット商品モデル : セット名
    ' セット商品モデル : 商品コード
    ' セット商品モデル : 型番
    ' セット商品モデル : 店舗ID[FK]
    ' セット商品モデル : 商品数
    ' セット商品モデル : 作成日時
    ' セット商品モデル : 最終更新日時
    ' 売上情報モデル : 売上情報ID
    ' 売上情報モデル : 商品コード[FK]
    ' 売上情報モデル : 仕入価格
    ' 売上情報モデル : 販売価格
    ' 売上情報モデル : 粗利
    ' 売上情報モデル : 粗利率
    ' 売上情報モデル : 店舗ID[FK]
    ' 売上情報モデル : 販売日
    ' 売上情報モデル : 最終更新日時
    ' 店舗情報モデル : 店舗ID
    ' 店舗情報モデル : 場所カテゴリ
    ' 店舗情報モデル : 住所
    ' 店舗情報モデル : 連絡先
    ' 店舗情報モデル : 店長
    ' 店舗情報モデル : 無効フラグ
    ' 店舗情報モデル : 作成日時
    ' 店舗情報モデル : 最終更新日時
    ログイン : 従業員番号
    ログイン : パスワード
    商品情報モデル : 型番
    商品情報モデル : 商品コード
    商品情報モデル : JANコード
    商品情報モデル : 商品画像
    商品情報モデル : 在庫場所
    商品情報モデル : カテゴリモデル
    商品情報モデル : 仕入価格
    ' カテゴリモデル : ノートPC
    ' カテゴリモデル : デスクトップPC
    ' カテゴリモデル : モニター
    ' カテゴリモデル : メモリ
    ' カテゴリモデル : HDD
    ' カテゴリモデル : SSD
}



ユーザ -- ログイン

@enduml