@startuml images/マスタ管理/商品マスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/商品マスタ
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "商品マスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "削除" #98fb98
    ' メインのモデルは赤
    class "商品情報モデル" #F5A9BC 
    class "カテゴリモデル"

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 登録
    ユーザ -- 編集
    ユーザ -- 削除
    参照 -- 商品情報モデル
    登録 -- 商品情報モデル 
    編集 -- 商品情報モデル 
    削除 -- 商品情報モデル
    商品情報モデル -- カテゴリモデル 
    商品情報モデル -- 在庫場所モデル
    
    'ドメインクラスの属性

}



ユーザ -- ログイン

@enduml