@startuml images/マスタ管理/商品マスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/商品マスタ
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "商品マスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    ' メインのモデルは赤
    class "商品情報モデル" #F5A9BC 
    class "カテゴリモデル" 
    package "ベンチマークマスタ"{
        class "GPUベンチマークモデル"
        class "CPUベンチマークモデル"
    }
    class "店舗マスタ"
    class "売上マスタ" 
    class "セット商品モデル"
    class "セット中間商品モデル"
    class "取置商品モデル"


    カテゴリモデル : カテゴリID
    カテゴリモデル : カテゴリ名











    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 登録
    ユーザ -- 編集
    ユーザ -- 詳細
    参照 -- 商品情報モデル
    登録 -- 商品情報モデル 
    編集 -- 商品情報モデル 
    詳細 -- 商品情報モデル
    商品情報モデル -- カテゴリモデル
    商品情報モデル -- 売上マスタ
    商品情報モデル -- 店舗マスタ
    商品情報モデル -- ベンチマークマスタ
    商品情報モデル -- 取置商品モデル
    商品情報モデル -- セット中間商品モデル
    商品情報モデル -- セット商品モデル
    'ドメインクラスの属性
    商品情報モデル : 型番
    商品情報モデル : 商品コード
    商品情報モデル : JANコード
    商品情報モデル : 商品画像
    商品情報モデル : 在庫場所
    商品情報モデル : カテゴリモデル
    商品情報モデル : 仕入価格
    カテゴリモデル : ノートPC
    カテゴリモデル : デスクトップPC
    カテゴリモデル : モニター
    カテゴリモデル : メモリ
    カテゴリモデル : HDD
    カテゴリモデル : SSD
}



ユーザ -- ログイン

@enduml