@startuml images/マスタ管理/売上マスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/売上マスタ
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "マスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "詳細" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "売上情報モデル" #F5A9BC 
    class "商品情報モデル"
    
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 編集
    ユーザ -- 詳細
    ユーザ -- ログイン
    参照 -- 売上情報モデル
    編集 -- 売上情報モデル
    詳細 -- 売上情報モデル
    売上情報モデル -- 商品情報モデル

    'ドメインクラスの属性
    売上情報モデル : 売上情報ID
    売上情報モデル : 商品コード[FK]
    売上情報モデル : 仕入価格
    売上情報モデル : 販売価格
    売上情報モデル : 粗利
    売上情報モデル : 粗利率
    売上情報モデル : 店舗ID[FK]
    売上情報モデル : 販売日
    売上情報モデル : 最終更新日時
    商品情報モデル : 型番
    商品情報モデル : 商品コード
    商品情報モデル : JANコード
    商品情報モデル : 商品画像
    商品情報モデル : 在庫場所
    商品情報モデル : カテゴリモデル
    商品情報モデル : 仕入価格
}





@enduml