@startuml images/マスタ管理/ベンチマークマスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/ベンチマークマスタ
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "マスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "詳細" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    package ベンチマークマスタ{
        class "GPUベンチマークモデル" #F5A9BC 
        class "CPUベンチマークモデル" #F5A9BC 
    }
    class "商品情報モデル"
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 編集
    ユーザ -- 詳細
    ユーザ -- ログイン
    参照 -- GPUベンチマークモデル
    編集 -- GPUベンチマークモデル
    詳細 -- GPUベンチマークモデル
    参照 -- CPUベンチマークモデル
    編集 -- CPUベンチマークモデル
    詳細 -- CPUベンチマークモデル
    GPUベンチマークモデル -- 商品情報モデル
    CPUベンチマークモデル -- 商品情報モデル

    'ドメインクラスの属性
    GPUベンチマークモデル : GPU名称[型番]
    GPUベンチマークモデル : 3DMark time spy graphics
    GPUベンチマークモデル : TDP
    GPUベンチマークモデル : コスパ
    GPUベンチマークモデル : ワットパフォーマンス
    GPUベンチマークモデル : 作成日時
    GPUベンチマークモデル : 最終更新日時
    CPUベンチマークモデル : CPU名称[型番]
    CPUベンチマークモデル : PassMark
    CPUベンチマークモデル : コア
    CPUベンチマークモデル : スレッド
    CPUベンチマークモデル : TDP
    CPUベンチマークモデル : 定格クロック
    CPUベンチマークモデル : 最大クロック
    CPUベンチマークモデル : コスパ
    CPUベンチマークモデル : 作成日時
    CPUベンチマークモデル : 最終更新日時
    ' 商品情報モデル : ER図の変更点待ち
    ログイン : 従業員番号
    ログイン : パスワード


}




@enduml