@startuml images/マスタ管理/ボトルネックマスタ
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/ボトルネックマスタ
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6

}

package "ボトルネックマスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "ボトルネックモデル" #F5A9BC
    package ベンチマークマスタ{
        class CPUベンチマークモデル
        class GPUベンチマークモデル
    }
    class 商品情報モデル
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ --> 参照 : > has-one
    ユーザ --> 編集
    ユーザ --> 登録
    ユーザ --> ログイン
    参照 --o ボトルネックモデル : > has-many
    編集 --o ボトルネックモデル
    登録 --o ボトルネックモデル
    ボトルネックモデル -- ベンチマークマスタ
    ボトルネックモデル -- 商品情報モデル

    ' ボトルネックモデル

    'ドメインクラスの属性
    ボトルネックモデル : ボトルネックID
    ボトルネックモデル : CPU名
    ボトルネックモデル : GPU名
    ボトルネックモデル : バランス
    ボトルネックモデル : WQHD
    ボトルネックモデル : 4K解像度
    ボトルネックモデル : ゲーム適正
    ボトルネックモデル : ゲーム配信
    ボトルネックモデル : 動画編集
    ボトルネックモデル : エンコード
    ボトルネックモデル : 作成日時
    ボトルネックモデル : 最終更新日時



}



@enduml