# Generated by Django 2.2.2 on 2021-11-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserve_at',
            field=models.DateField(auto_now_add=True, verbose_name='予約日時'),
        ),
    ]
