@startuml sequence

hide footbox
header 営業情報管理システム
title マスタ管理/ベンチマーク情報を削除する

' actor "" as 
actor "管理者\n正規社員" as a1 

' boundary "" as 
boundary "ログイン済\nホーム画面" as b1
boundary "ベンチマーク\n情報一覧画面" as b2
boundary "詳細画面" as b3

' control "" as c
control "情報を取得する" as c1
' ↑ベンチマークマスタ情報を取得するだったんだけど変更していいかな
control "削除する" as c2

' entity "" as e
entity "ベンチマーク情報" as e1

a1 -> b1
activate b1
b1 -> c1
deactivate b1
activate c1
c1 -> e1
activate e1
e1 --> c1
c1 --> b2
activate b2
b2 -> c1
deactivate b2
c1 -> e1
e1 --> c1
c1 --> b3
activate b3
deactivate c1
b3 -> c2
deactivate b3
activate c2
c2 -> e1
e1 --> c2
deactivate e1
c2 --> b2
deactivate c2
activate b2
b2 --> a1 
deactivate b2


@enduml