# Generated by Django 2.2.2 on 2021-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earningmas', '0003_auto_20211126_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earninginfo',
            name='sale_date',
            field=models.DateField(auto_now_add=True, verbose_name='販売日'),
        ),
    ]
