# Generated by Django 2.2.2 on 2021-11-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='employment_status',
            field=models.SmallIntegerField(choices=[(0, '管理者'), (1, '店長'), (2, '正規社員'), (3, '非正規社員')], verbose_name='雇用形態'),
        ),
    ]
