@startuml ../../images/取置予約管理/取置予約管理_削除

hide footbox
header 営業情報管理システム
title 商品情報管理/取置予約をする

' actor "" as a
actor "正規社員\n非正規社員" as a1

' boundary "" as b
boundary "ログイン済\nホーム画面" as b1
boundary "取置予約\n一覧画面" as b2
boundary "詳細画面" as b3

' control "" as c
control "取置予約一覧\nコントローラ" as c1
control "詳細\nコントローラ" as c2

' entity "" as e
entity "取置商品情報" as e1

@enduml