@startuml ../../images/店舗情報参照/店舗情報参照

hide footbox
header 営業情報管理システム
title 人事情報管理/店舗情報を参照する


' actor "" as 
actor "正規社員\n非正規社員" as a1

' boundary "" as 
boundary "ログイン済み\nホーム画面" as b1
boundary "店舗情報\n一覧画面" as b2
boundary "詳細画面" as b3

' control "" as 
control "店舗情報一覧\nコントローラ" as c1
control "詳細\nコントローラ" as c2

' entity "" as
entity "店舗情報" as e1


a1 -> b1 :「店舗情報」を押下する()
activate b1
b1 -> c1 : 画面の表示を要求する()
deactivate b1
activate c1
c1 -> e1 : 情報を要求する() 
activate e1
e1 --> c1 : 情報を送信する
deactivate
c1 --> b2 : 画面を組み立てる
activate b2
b2 --> a1 : 画面を表示する
opt 店舗情報がない場合
c1 --> b2 : 画面を組み立てる 
deactivate c1
b2 --> a1 : メッセージを表示する
end
a1 -> b2 : 表示したい情報を選択する
b2 -> c2 : 画面の表示を要求する()
deactivate b2
activate c2
c2 -> e1 : 情報を要求する() 
activate e1
e1 --> c2 : 情報を送信する
deactivate e1
b3 <-- c2 : 画面を組み立てる
deactivate c2
activate b3
a1 <-- b3 : 画面を表示する
deactivate



@enduml