# Generated by Django 2.2.2 on 2021-11-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeemas',
            fields=[
                ('id', models.AutoField(db_column='employee_id', editable=False, primary_key=True, serialize=False, verbose_name='従業員ID')),
                ('store_id', models.SmallIntegerField(choices=[(0, '-'), (1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], verbose_name='店舗ID')),
                ('employment_status', models.CharField(max_length=5, verbose_name='雇用形態')),
                ('name', models.CharField(max_length=30, verbose_name='氏名')),
                ('ruby_name', models.CharField(max_length=30, verbose_name='氏名(カナ)')),
                ('tel_num', models.CharField(max_length=13, verbose_name='電話番号')),
                ('gender', models.SmallIntegerField(choices=[(0, '-'), (1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], verbose_name='従業員ID')),
                ('birthday', models.TimeField(verbose_name='生年月日')),
                ('invalid_flg', models.SmallIntegerField(choices=[(0, '-'), (1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], verbose_name='無効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('lastlogin_at', models.DateTimeField(auto_now_add=True, verbose_name='最終ログイン日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '従業員情報モデル',
            },
        ),
    ]
