@startuml ../images/商品情報管理/検索
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報管理/検索
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6

}
package "検索"{
'ユーザや外部システム
    mix_actor "ユーザ"
    class "商品情報検索" #98fb98
    class "ボトルネック検索" #98fb98
    class "ベンチマーク検索" #98fb98
    class "商品情報モデル" #F5A9BC
    class "ベンチマークマスタ" #F5A9BC
    class "商品情報モデル" #F5A9BC
    class "店舗情報モデル"
    package "マスタ管理"{
        package ベンチマークマスタ{
            class "CPUベンチマークモデル" #F5A9BC
            class "GPUベンチマークモデル" #F5A9BC
        }
        class "ボトルネックモデル" #F5A9BC
    }
    
}
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ --> 商品情報検索
    ユーザ --> ボトルネック検索
    ユーザ --> ベンチマーク検索 : > has-one
    ユーザ --> ログイン
    商品情報検索 --o 商品情報モデル
    ボトルネック検索 --o 商品情報モデル
    ボトルネック検索 --o ボトルネックモデル
    ベンチマーク検索 --o 商品情報モデル: > has-many
    ベンチマーク検索 --o ベンチマークマスタ
    商品情報モデル o-- 店舗情報モデル
    ' 商品情報モデル o-- マスタ管理

    'ドメインクラスの属性
    商品情報モデル : 商品コード
    商品情報モデル : 型番
    商品情報モデル : 店舗ID[FK]
    商品情報モデル : カテゴリモデル
    商品情報モデル : メーカー名
    商品情報モデル : 商品状態
    商品情報モデル : 仕入価格
    商品情報モデル : 商品画像
    商品情報モデル : 備考
    商品情報モデル : 作成日時
    商品情報モデル : 最終更新日時
    ログイン : 従業員ID
    ログイン : パスワード
@enduml