# Generated by Django 2.2.2 on 2022-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='employee_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='従業員ID'),
        ),
    ]
