@startuml ../../images/見積/販売価格見積

hide footbox
header 営業情報管理システム
title 商品情報管理/販売価格を見積する

' actor "" as a
actor "正規社員\n非正規社員" as a1

' boundary "" as b
boundary "ログイン済\nホーム画面" as b1
boundary "見積画面" as b2
boundary "お客様用\n見積画面" as b3

' control "" as c
control "見積\nコントローラ" as c1
control "お客様用見積\nコントローラ" as c2

' entity "" as e
entity "商品情報" as e1

@enduml