@startuml シーケンス図

hide footbox
header 営業情報管理システム/人事情報管理
title 正規非正規ユーザの権限を編集

actor "管理者\n(権限)" as Manager
boundary "メ二ュー\n画面" as MenuSc
Manager -> MenuSc : マスタ管理\nを選択
activate MenuSc

create boundary "マスタ管理\n画面" as MastSc
MenuSc -> MastSc : 表示()
deactivate
activate MastSc

Manager -> MastSc : <back:#25b7c0>○○</back>管理を選択

create boundary "<back:#25b7c0>○○</back>登録\n画面" as StaffRegiSc
MastSc -> StaffRegiSc : 表示()
deactivate
activate StaffRegiSc

Manager -> StaffRegiSc : <back:#25b7c0>○○</back>入力

create entity "<back:#25b7c0>○○</back>\nモデル" as StaffObj
StaffRegiSc -> StaffObj : <back:#25b7c0>○○</back>登録()
deactivate
activate StaffObj

StaffObj -> StaffRegiSc : 登録しました\nポップを表示()
deactivate
activate StaffRegiSc
deactivate

@enduml