@startuml sequence

hide footbox
header 営業情報管理システム
title ログイン

' actor "" as 
actor "管理者\n正規社員\n非正規社員" as a1

' boundary "" as
boundary "ホーム画面" as b1
boundary "ログイン済\nホーム画面" as b2

' control "" as 
control "登録を検証する" as c1
control "表示する" as c2

' entity "" as
entity "従業員情報" as e1

a1 -> b1
activate b1
b1 -> c1 : フォームに情報を入力\n「ログイン」を押下()
activate c1
opt 情報に間違いがある場合
c1 --> b1 : メッセージを表示する
b1 --> a1
deactivate b1
end
c1 -> e1 : 登録情報を\n要求する() 
activate e1
e1 --> c1 : 要求された\n情報を送信する
deactivate e1
c1 -> c2 : 画面の表示を\n要求する()
deactivate c1
alt 検証成功
activate c2
c2 --> b2 : 検証結果を基に\n画面を表示する
activate b2
b2 --> a1
deactivate b2
else 検証失敗
c2 --> b1 : 検証結果を基に\n画面を表示する
deactivate c2
activate b1
b1 --> a1
deactivate b1
end



@enduml