@startuml シーケンス図

hide footbox
header 営業情報管理システム/人事情報管理
title <back:#25b7c0>従業員情報</back>管理

actor "管理者\n正規社員" as Act
boundary "従業員情報\n一覧画面" as StaffListSc
boundary "従業員詳細情報画面" as StaffScｍｍ
control "従業員情報表示する\nコントローラ" as StaffCl
entity "従業員情報" as StaffDB


' Act -> StaffListSc : 任意の従業員を選択し押下する
' StaffListSc -> StaffCl : 従業員詳細情報画面を要求する()
' StaffCl -> StaffDB : 従業員のデータを要求する()
' StaffCl <-- StaffDB : 従業員のデータを返す()
' StaffSc <-- StaffCl : 従業員詳細情報画面を組み立てる()
' Act <-- StaffSc : 従業員詳細情報を表示する()


@enduml