@startuml シーケンス図

hide footbox
header 営業情報管理システム/人事情報管理
title <back:#25b7c0>従業員情報</back>管理

actor "管理者\n正規社員" as Act
boundary "ログイン済み\nホーム画面" as HomeSc
boundary "従業員情報\n一覧画面" as StaffListSc
boundary "新規登録画面" as RegiSc
boundary "従業員詳細情報画面" as StaffSc
boundary "従業員情報編集画面" as UpdateSc
control "従業員情報\nコントローラ" as StaffCl
control "新規登録\nコントローラ" as RegiCl
control "更新\nコントローラ" as UpdateCl
control "削除\nコントローラ" as DeleteCl
control "入力データを検証する" as JudgeCl

control "登録する" as Regi
entity "従業員情報" as StaffDB

Act -> HomeSc : 「従業員情報」を押下する
HomeSc -> StaffCl : 従業員情報一覧画面\nを要求する()
StaffCl -> StaffDB : 従業員のデータを要求する()
StaffCl <-- StaffDB : 従業員のデータを返す()
StaffListSc <-- StaffCl : 一覧画面を組み立てる()
Act <-- StaffListSc : 一覧画面を表示する()

@enduml