@startuml シーケンス図

hide footbox
header 営業情報管理システム/人事情報管理
title <back:#25b7c0>従業員情報</back>管理

actor "管理者\n正規社員" as Act
boundary "従業員情報\n一覧画面" as StaffListSc
boundary "新規登録画面" as RegiSc
boundary "従業員詳細情報画面" as StaffSc
boundary "従業員情報編集画面" as UpdateSc
control "従業員情報\nコントローラ" as StaffCl
control "新規登録\nコントローラ" as RegiCl
control "更新\nコントローラ" as UpdateCl
control "削除\nコントローラ" as DeleteCl
control "入力データを検証する" as JudgeCl

control "登録する" as Regi
entity "従業員情報" as StaffDB



Act -> StaffListSc : 新規登録を押下する
StaffListSc -> RegiCl : 新規登録画面を要求する()
RegiSc <-- RegiCl : 新規登録画面を組み立てる()
Act <-- RegiSc : 新規登録画面を表示する()
Act -> RegiSc : 従業員情報を入力する
RegiSc -> RegiCl : 登録結果画面を要求する()
RegiCl -> JudgeCl : 入力データの検証を要求する()
    alt successful case
        RegiCl <-- JudgeCl : 成功フラグを返す()
        RegiCl <-> StaffDB : 従業員情報を登録する()
        RegiSc <-- RegiCl : 登録結果画面を組み立てる()
        Act <-- RegiSc : 「登録しました」として表示する()
    else fail
        RegiCl <-- JudgeCl : 失敗フラグを返す()
        RegiSc <-- RegiCl : 登録結果画面を組み立てる()
        Act <-- RegiSc : エラー部分を示し表示する()
    end



@enduml