# Generated by Django 2.2.2 on 2021-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmas', '0002_auto_20211201_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='id',
            field=models.CharField(db_column='item_code', max_length=9, primary_key=True, serialize=False, verbose_name='商品コード'),
        ),
    ]
