# Generated by Django 2.2.2 on 2022-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmas', '0005_itemspecification_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='最終更新日時'),
        ),
    ]
