@startuml sequence

hide footbox
header 営業情報管理システム
title マスタ管理/売上情報を参照する

' actor "" as a
actor "管理者" as a1

' boundary "" as b
boundary "ログイン済ホーム画面" as b1
boundary "売上情報一覧画面" as b2
boundary "詳細画面" as b3

' control "" as c
control "取得する" as c1

' entity "" as e
entity "売上情報" as e1

a1 -> b1
activate b1
b1 -> c1: 「売上情報マスタ」を押下する
deactivate b1
activate c1
c1 -> e1: 情報を\n要求する()
activate e1
e1 --> c1: 情報を返す
c1 --> b2: 画面を表示する
activate b2
opt 売上情報がない場合
b2 --> a1 : メッセージを表示する
end
b2 -> c1: 情報を選択する
deactivate b2
c1 -> e1:情報を\n要求する()
e1 --> c1:情報を返す
deactivate e1
c1 --> b3:画面を表示する
deactivate c1
activate b3
b3 --> a1
deactivate b3

@enduml