# Generated by Django 2.2.2 on 2022-01-19 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earningmas', '0003_remove_earninginfo_gross_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earninginfo',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='従業員ID'),
        ),
    ]
