# Generated by Django 2.2.2 on 2022-01-18 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storemas', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only num characters are allowed.')], verbose_name='従業員番号'),
        ),
    ]
