@startuml images/商品情報管理/在庫
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報管理/在庫
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "在庫" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    class "在庫商品" #F5A9BC
    class "取置予約"
    class "商品情報"
}
    package "マスタ管理"{
    }
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 登録
    ユーザ -- 編集
    ユーザ -- 詳細
    ユーザ -- ログイン
    参照 -- 在庫商品
    編集 -- 在庫商品
    詳細 -- 在庫商品
    在庫商品 -- 取置予約
    在庫商品 -- 商品情報
    在庫商品-- マスタ管理

    'ドメインクラスの属性




@enduml