@startuml ../images/商品情報モデル管理/取置商品モデル
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報モデル管理/取置商品モデル
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6

}

package "取置商品モデル" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    class "取置商品モデル" #F5A9BC
    class "商品情報モデル"
}
    ' package "マスタ管理"{
    '     ' package ""{}
    '     ' package ""{}
    '     ' package ""{}
    '     }

    'モデル同士の関係
    ユーザ --> 参照
    ユーザ --> 登録
    ユーザ --> 編集
    ユーザ --> 詳細 : > has-one
    ユーザ --> ログイン
    参照 --o 取置商品モデル
    登録 --o 取置商品モデル
    編集 --o 取置商品モデル
    詳細 --o 取置商品モデル : > has-many
    取置商品モデル o-- 商品情報モデル
    ' 取置商品モデル -down- マスタ管理

    'ドメインクラスの属性
    取置商品モデル : 取置商品ID[FK]
    取置商品モデル : 商品コード
    取置商品モデル : 店舗ID[FK]
    取置商品モデル : 予約者氏名
    取置商品モデル : 連絡先
    取置商品モデル : 予約日時
    取置商品モデル : 最終更新日時


    ' 商品情報モデル : 型番
    ' 商品情報モデル : 商品コード
    ' 商品情報モデル : JANコード
    ' 商品情報モデル : 商品画像
    ' 商品情報モデル : 在庫場所
    ' 商品情報モデル : カテゴリ
    ' 商品情報モデル : 仕入価格
    ログイン : 従業員ID
    ログイン : パスワード




@enduml