@startuml images/商品情報管理/取置予約
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報管理/取置予約
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "マスタ" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    class "取置予約" #F5A9BC
    class "商品情報" 
    class "在庫商品" 
}
    package 人事管理{
        class "店舗情報モデル" 
    }
    package "マスタ管理"{
        }


    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 登録
    ユーザ -- 編集
    ユーザ -- 詳細
    ユーザ -- ログイン
    参照 -- 取置予約
    登録 -- 取置予約
    編集 -- 取置予約
    詳細 -- 取置予約
    取置予約 -- 商品情報
    取置予約-- 在庫商品
    取置予約 -down- 店舗情報モデル
    取置予約-down- マスタ管理

    'ドメインクラスの属性
    ' 在庫商品と取置予約のフィードがない
    ' 商品情報 : 型番
    ' 商品情報 : 商品コード
    ' 商品情報 : JANコード
    ' 商品情報 : 商品画像
    ' 商品情報 : 在庫場所
    ' 商品情報 : カテゴリ
    ' 商品情報 : 仕入価格
    ログイン : 従業員番号
    ログイン : パスワード




@enduml