@startuml images/商品情報管理/見積
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報管理/見積
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}
package "見積" {
    mix_actor "ユーザ"
        class "参照(お客様用)" #98fb98
        class "参照" #98fb98
        class "見積" #F5A9BC
        class "取置予約" 
}
        package "マスタ管理"{
            }


        ' class "" #F5A9BC
        ' class "" #ffd700

    'モデル同士の関係
    ' 見積
    ユーザ --> 参照 : > has-one
    ユーザ --> "参照(お客様用)"
    ユーザ --> ログイン
    参照 --o 見積 : > has-many
    "参照(お客様用)" --o 見積
    見積 o-- 取置予約
    見積 o-- マスタ管理
    ログイン : 従業員番号
    ログイン : パスワード

@enduml