@startuml images/商品情報管理/商品情報モデル
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報管理/商品情報モデル
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
    class "権限編集"
}
package "商品情報モデル" {
    mix_actor "ユーザ"
        class "参照(客用)" #98fb98
        class "参照" #98fb98
        class "商品情報モデル" #F5A9BC
        class "取置商品モデル" 
}

' package "マスタ管理"{
' }

    ユーザ --> 参照 : > has-one
    ユーザ --> "参照(客用)"
    ユーザ --> ログイン
    参照 --o 商品情報モデル : > has-many
    "参照(客用)" --o 商品情報モデル
    商品情報モデル o-- 取置商品モデル
    ' 商品情報モデル o-- マスタ管理
    ログイン : 従業員番号
    ログイン : パスワード
    
    商品情報モデル : 商品コード
    商品情報モデル : JANコード
    商品情報モデル : 型番
    商品情報モデル : メーカー名
    商品情報モデル : 店舗ID
    商品情報モデル : カテゴリ
    商品情報モデル : 商品状態
    商品情報モデル : 仕入価格
    商品情報モデル : 商品画像
    商品情報モデル : 作成日時
    商品情報モデル : 最終更新日時

@enduml