@startuml images/商品情報管理/売上
' ヘッダー
header 営業情報管理システム
' タイトル
title 商品情報管理/売上
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "売上" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "登録" #98fb98
    class "編集" #98fb98
    class "参照" #98fb98
    class "詳細" #98fb98
    class "売上情報" #F5A9BC
    class "商品情報"
}
    package "マスタ管理"{
    }
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 登録
    ユーザ -- 編集
    ユーザ -- 詳細
    ユーザ -- ログイン
    参照 -- 売上情報
    登録 -- 売上情報
    編集 -- 売上情報
    詳細 -- 売上情報
    売上情報 -- 商品情報
    売上情報 -- マスタ管理

    'ドメインクラスの属性
    ' 商品情報 : 型番
    ' 商品情報 : 商品コード
    ' 商品情報 : JANコード
    ' 商品情報 : 商品画像
    ' 商品情報 : 在庫場所
    ' 商品情報 : カテゴリ
    ' 商品情報 : 仕入価格
    売上情報 : 販売履歴
    ログイン : 従業員ID
    ログイン : パスワード




@enduml