@startuml ../../images/在庫管理/セット商品管理_参照

hide footbox
header 営業情報管理システム
title 人事情報管理/セット商品情報を参照する

' actor "" as a
actor "正規社員\n非正規社員" as a1

' boundary "" as b
boundary "ログイン済\nホーム画面" as b1
boundary "セット商品\n一覧画面" as b2
boundary "詳細画面" as b3

' control "" as c
control "セット商品一覧\nコントローラ" as c1
control "詳細\nコントローラ" as c2

' entity "" as e
entity "セット商品情報" as e1

a1 -> b1 : 「セット商品情報」を押下する
activate b1
b1 -> c1 : 画面の表示を要求する()
deactivate b1
activate c1
c1 -> e1 : 情報を要求する()
activate e1
e1 --> c1 : 情報を送信する
deactivate e1
opt 情報が登録されていない場合
c1 --> b2 : 画面を組み立てる
activate b2
b2 --> a1 : メッセージを表示する
end
c1 --> b2 : 画面を組み立てる
deactivate c1
b2 --> a1 : 画面を表示する
a1 -> b2 : 情報を選択する
b2 -> c2 : 画面の表示を要求する()
deactivate b2
activate c2
c2 -> e1 : 情報を要求する()
activate e1
e1 --> c2 : 情報を送信する
deactivate e1
c2 -> b3 : 画面を組み立てる
deactivate c2 
activate b3
b3 --> a1 : 画面を表示する
deactivate b3


@enduml