# Generated by Django 2.2.2 on 2022-01-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_nm', models.CharField(blank=True, max_length=60, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_tamesi',
            },
        ),
    ]
