# Generated by Django 2.2.2 on 2021-09-27 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Householdaccountbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('choice', models.CharField(choices=[('out', '支出'), ('in', '収入')], default='', max_length=10, verbose_name='出入金')),
                ('genre', models.CharField(choices=[('food', '食品'), ('clothing', '衣類'), ('favo', '娯楽'), ('payment', '支払い'), ('salary', '給料'), ('other', 'その他')], default='', max_length=10, verbose_name='ジャンル')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='品名')),
                ('quanity', models.PositiveIntegerField(null=True, verbose_name='数量')),
                ('money', models.PositiveIntegerField(verbose_name='金額')),
                ('content', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Householdaccountbook',
            },
        ),
    ]
