# Generated by Django 2.2.2 on 2022-02-03 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220203_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only num characters are allowed.')], verbose_name='従業員番号'),
        ),
    ]
