# Generated by Django 2.2.2 on 2022-01-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earningmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earninginfo',
            name='item_code',
            field=models.ForeignKey(db_column='item_code', limit_choices_to={'item_status': 1}, on_delete=django.db.models.deletion.CASCADE, to='itemmas.ItemInfo', verbose_name='商品コード'),
        ),
    ]
