# Generated by Django 2.2.2 on 2021-11-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.CharField(db_column='item_code', editable=False, max_length=9, primary_key=True, serialize=False, verbose_name='商品コード')),
                ('model_number', models.CharField(max_length=60, verbose_name='型番')),
                ('category', models.SmallIntegerField(choices=[(0, 'ノートPC'), (1, 'デスクトップ'), (2, 'モニター'), (3, 'メモリ'), (4, 'HDD'), (5, 'SDD'), (6, 'Office'), (7, 'その他')], verbose_name='カテゴリ')),
                ('manufacturer_name', models.CharField(max_length=30, verbose_name='メーカー名')),
                ('item_status', models.CharField(max_length=10, verbose_name='商品状態')),
                ('purchase_price', models.IntegerField(verbose_name='仕入価格')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品画像')),
                ('remarks', models.TextField(verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('store_id', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗ID')),
            ],
            options={
                'verbose_name_plural': '商品情報モデル',
            },
        ),
    ]
