# Generated by Django 2.2.2 on 2021-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpubenchmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpubench',
            name='gpu_name',
            field=models.CharField(max_length=60, verbose_name='GPU名称'),
        ),
    ]
