# Generated by Django 2.2.2 on 2022-01-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottleneck',
            fields=[
                ('id', models.AutoField(db_column='bottleneck_id', editable=False, primary_key=True, serialize=False, verbose_name='ボトルネックID')),
                ('cpu_name', models.CharField(max_length=60, verbose_name='CPU名')),
                ('gpu_name', models.CharField(max_length=60, verbose_name='GPU名')),
                ('balance', models.SmallIntegerField(choices=[(1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], default=4, verbose_name='バランス')),
                ('wqhd', models.SmallIntegerField(choices=[(1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], default=4, verbose_name='WQHD')),
                ('four_k', models.SmallIntegerField(choices=[(1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], default=4, verbose_name='4K解像度')),
                ('game_appropriate', models.SmallIntegerField(choices=[(1, 'S+'), (2, 'S'), (3, 'S-'), (4, 'A+'), (5, 'A'), (6, 'A-'), (7, 'B+'), (8, 'B'), (9, 'B-'), (10, 'C+'), (11, 'C'), (12, 'C-'), (13, 'D+'), (14, 'D'), (15, 'D-')], default=8, verbose_name='ゲーム適正')),
                ('game_delivery', models.SmallIntegerField(choices=[(1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], default=4, verbose_name='ゲーム配信')),
                ('video_editing', models.SmallIntegerField(choices=[(1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], default=4, verbose_name='動画編集')),
                ('encode', models.SmallIntegerField(choices=[(1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], default=4, verbose_name='エンコード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name_plural': 'ボトルネックモデル',
            },
        ),
    ]
