@startuml sequence

hide footbox
header 営業情報管理システム
title マスタ管理/商品情報を参照する

' actor "" as a
actor "管理者" as a1

' boundary "" as b
boundary "ログイン済\nホーム画面" as b1
boundary "商品情報\n一覧画面" as b2
boundary "詳細画面" as b3

' control "" as c
control "取得する" as c1

' entity "" as e
entity "商品情報" as e1

@enduml