# Generated by Django 2.2.2 on 2022-01-12 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemmas', '0001_initial'),
        ('storemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.AutoField(db_column='set_item_id', editable=False, primary_key=True, serialize=False, verbose_name='セット商品ID')),
                ('set_name', models.CharField(max_length=30, verbose_name='セット名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('set_item', models.ManyToManyField(to='itemmas.ItemInfo')),
                ('store_id', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗ID')),
            ],
            options={
                'verbose_name_plural': '売上情報モデル',
            },
        ),
    ]
