@startuml シーケンス図

hide footbox
header 営業情報管理システム
title 人事情報管理/店舗情報を参照する


' actor "" as 
actor "正規社員\n非正規社員" as a1

' boundary "" as 
boundary "ログイン済み\nホーム画面" as b1
boundary "店舗情報\n一覧画面" as b2
boundary "詳細画面" as b3

' control "" as 
control "店舗情報を取得する" as c1

' entity "" as
entity "店舗情報" as e1


' 長谷川
activate a1
a1 -> b1
activate b1
b1 -> c1 : 「店舗情報」を押下する()
deactivate
activate c1
c1 <-> e1 : aaaaaaa
b2 <-- c1
deactivate
activate b2
a1 <-- b2
a1 -> b2
b2 -> b3 : 表示したい項目を\n選択し押下する()
deactivate
activate b3
a1 <-- b3
deactivate



@enduml