# Generated by Django 2.2.2 on 2021-11-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpuBench',
            fields=[
                ('id', models.AutoField(db_column='gpu_bench_id', editable=False, primary_key=True, serialize=False, verbose_name='GPUベンチマークID')),
                ('gpu_name', models.CharField(max_length=30, verbose_name='GPU名称')),
                ('marktimespygraphics', models.IntegerField(verbose_name='Mark Time Spy Graphics')),
                ('tdp', models.IntegerField(verbose_name='TDP')),
                ('cost_performance', models.FloatField(max_length=4, verbose_name='コスパ')),
                ('wattage_performance', models.FloatField(max_length=6, verbose_name='ワットパフォーマンス')),
                ('list_price', models.IntegerField(verbose_name='定価')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'GpuBench',
            },
        ),
    ]
