# Generated by Django 2.2.2 on 2021-11-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.CharField(db_column='employee_id', editable=False, max_length=13, primary_key=True, serialize=False, verbose_name='従業員ID')),
                ('employment_status', models.CharField(choices=[(0, '管理者'), (1, '店長'), (2, '正規社員'), (3, '非正規社員')], max_length=5, verbose_name='雇用形態')),
                ('name', models.CharField(max_length=30, verbose_name='氏名')),
                ('ruby_name', models.CharField(max_length=30, verbose_name='氏名(カナ)')),
                ('tel_num', models.CharField(max_length=13, verbose_name='電話番号')),
                ('gender', models.SmallIntegerField(choices=[(0, '男性'), (1, '女性')], verbose_name='性別')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('invalid_flg', models.BooleanField(verbose_name='無効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('lastlogin_at', models.DateTimeField(auto_now_add=True, verbose_name='最終ログイン日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store_id', models.ForeignKey(db_column='store_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗ID')),
            ],
            options={
                'verbose_name_plural': '従業員情報モデル',
            },
        ),
    ]
