@startuml マスタ管理
' left to right direction

hide circle
hide method

package ユーザ内容 {
  mix_actor 管理者
  mix_actor 正規社員
  mix_actor 非正規社員
}
package ドメインモデル図_マスタ管理・その他 {
  class 商品情報 #F5A9BC
  class ベンチマーク 
  class 売上情報 
  class 従業員情報 #F5A9BC
  class 店舗情報 
  class 権限管理 
  class ログイン #A9C6F6
  mix_actor ユーザ

  権限管理 : 管理者
  権限管理 : 正規社員
  権限管理 : 非正規社員
  従業員情報 : 従業員番号
  従業員情報 : 役職（権限）
  従業員情報 : 氏名
  従業員情報 : 住所
  従業員情報 : 電話番号
  従業員情報 : 緊急連絡先
  従業員情報 : 性別
  従業員情報 : 年齢
  従業員情報 : 生年月日
  従業員情報 : 主な店舗
  商品情報 : 型番
  商品情報 : 商品コード
  商品情報 : JANコード
  商品情報 : 商品画像
  商品情報 : 在庫場所
  売上情報 : 販売履歴
  店舗情報 : 店舗A
  店舗情報 : 店舗B
  店舗情報 : 店舗C
  店舗情報 : 店舗D
  ログイン : 従業員ID
  ログイン : パスワード


  従業員情報 -left- 店舗情報
  商品情報 -left- 売上情報
  ユーザ -up-> ログイン
  従業員情報 -> 権限管理 : has-one
  商品情報 -- ベンチマーク : is-a-kind-of
}
@enduml