@startuml ドメインモデル図_人事情報管理
' left to right direction

hide circle
hide method

package 従業員内容 {
  mix_actor 正規社員 
  mix_actor 非正規社員
}

正規社員 -[hidden]- 非正規社員

package 人事情報管理_ドメインモデル図{
  mix_actor 従業員
  class 従業員情報 #F5A9BC
  class 店舗情報
  class 勤務店舗状況 
  class ログイン #A9C6F6

  従業員情報 -[hidden]left- 従業員

  ログイン : 従業員番号
  ログイン : パスワード

  従業員情報 : 従業員番号
  従業員情報 : 氏名
  従業員情報 : 住所
  従業員情報 : 電話番号
  従業員情報 : 性別
  従業員情報 : 年齢
  従業員情報 : 生年月日
  従業員情報 : 主な店舗
  店舗情報 : 店舗名
  店舗情報 : 住所
  店舗情報 : 連絡先
  店舗情報 : 店長
  店舗情報 : 主な従業員
  勤務店舗状況 : 店舗名
  勤務店舗状況 : 従業員数
  勤務店舗状況 : 責任者

  従業員 -up-> ログイン : has-one 
  従業員 <- 従業員情報 : has-many
  従業員情報 -right-> 店舗情報 : has-one 
  従業員情報 --> 勤務店舗状況 : has-one
  店舗情報 <|-- 勤務店舗状況 : is-a
  ' 従業員情報 -[hidden]- 店舗情報
  ' 従業員情報 --> 店舗情報
  店舗情報 o--> 従業員情報 : has-many
  ' 店舗情報 -[hidden]down- 勤務店舗状況

  ' 正規社員 -[hidden]up- 従業員情報 

  ' 正規社員 -> 従業員情報 : has-one
  ' 非正規社員 -> 従業員情報 : has-one
  ' 非正規社員 -> 勤務店舗状況 : has-one
  ' 店舗情報 o--> 勤務店舗状況 :has-many
}
@enduml