@startuml シーケンス図

' 下アイコン除去
hide footbox
' ヘッダー
header 営業情報管理システム
' タイトル
title 人事情報管理/従業員情報を参照する


' actor "" as 
actor "管理者\n正規社員" as a1

' boundary "" as 
boundary "ログイン済み\nホーム画面" as b1
boundary "従業員情報\n一覧画面" as b2
boundary "詳細\n画面" as b3

' control "" as 
control "従業員情報一覧\nコントローラ" as c1
control "詳細\nコントローラ" as c2

' entity "" as
entity "従業員情報" as e1


' ログイン済みホーム画面から一覧表示までのシーケンス
a1 -> b1 : 「従業員情報」を押下する
activate b1
b1 -> c1 : 従業員情報一覧画面を要求する()
deactivate b1
activate c1
c1 -> e1 : 登録情報を\n要求する()
activate e1
c1 <-- e1 : 要求された\n情報を送信する
deactivate e1
b2 <-- c1 : 取得情報を基に画面を表示する
activate b2

' 代替フロー
opt 基本フロー②で参照したい従業員情報がない場合
b2 <-- c1 : 取得情報を基に画面を表示する\n「データがありません」
deactivate c1
end

activate b2
a1 <-- b2
a1 -> b2 : 参照したい情報を選択し押下する
b2 -> c2 : 詳細画面を要求する()
deactivate b2
activate c2


c2 -> e1 : 登録情報を\n要求する()
activate e1
c2 <-- e1 : 要求された\n情報を送信する
deactivate e1
b3 <- c2 : 詳細画面を表示する()
deactivate c2
activate b3
a1 <-- b3
deactivate b3



@enduml