@startuml シーケンス図
' 下アイコン除去
hide footbox
' ヘッダー
header 営業情報管理システム/人事情報管理
' タイトル
title 従業員情報管理_削除


' アイコン
actor "管理者\n正規社員" as a1
boundary "ログイン済み\nホーム画面" as b1
boundary "従業員情報\n一覧画面" as b2
boundary "詳細画面" as b3
control "従業員情報を取得する" as c1
control "表示する" as c2
entity "従業員情報" as e1



' ログイン済みホーム画面から一覧表示までのシーケンス
activate a1
a1 -> b1 : 「従業員情報」を押下する
activate b1
b1 -> c1 : 従業員情報一覧画面\nを要求する
deactivate
activate c1

c1 -> e1 : 従業員のデータを要求する
activate e1
c1 <-- e1 : 従業員のデータを返す
deactivate
b2 <-- c1 : 一覧画面を組み立てる
deactivate
activate b2
a1 <-- b2 : 一覧画面を表示する


' 詳細画面表示までのシーケンス
a1 -> b2 : 参照したいデータを選択し押下する
b2 -> c2 : 詳細画面を要求する
deactivate
activate c2
b3 <-- c2
deactivate
activate b3
a1 <-- b3 : 詳細画面を表示する
deactivate


' 従業員情報を削除するシーケンス
group "編集する"



end


@enduml