# Generated by Django 2.2.2 on 2022-01-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earningmas', '0002_auto_20220115_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earninginfo',
            name='gross_profit_margin',
        ),
    ]
