# Generated by Django 2.2.2 on 2022-01-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgMstBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_cd', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'ig_mst_brand',
            },
        ),
        migrations.CreateModel(
            name='IgMstProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_nm', models.CharField(blank=True, max_length=60, null=True)),
                ('product_url', models.TextField(blank=True, null=True)),
                ('brand_cd', models.ForeignKey(db_column='brand_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamesi.IgMstBrand')),
            ],
            options={
                'db_table': 'ig_mst_product',
            },
        ),
    ]
