# Generated by Django 2.2.2 on 2022-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmas', '0004_auto_20220119_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemspecification',
            name='memory',
            field=models.SmallIntegerField(blank=True, default='0', verbose_name='RAM'),
        ),
    ]
