@startuml シーケンス図
' 下アイコン除去
hide footbox
' ヘッダー
header 営業情報管理システム
' タイトル
title 人事情報管理/勤務店舗状況を参照する


' actor "" as 
actor "正規社員\n非正規社員" as a1

' boundary "" as 
boundary "ログイン済\nホーム画面" as b1
boundary "勤務店舗状況\n一覧画面" as b2

' control "" as 
control "勤務店舗\n状況を\n取得する" as c1

' entity "" as
entity "従業員情報" as e1


' 長谷川

a1 -> b1
activate b1
b1 -> c1 : 「勤務店舗状況」を押下する()
deactivate
activate c1
c1 -> e1 : 登録情報を\n要求する() 
activate e1
e1 --> c1 : 要求された\n情報を送信する
deactivate
b2 <-- c1
deactivate
activate b2
a1 <-- b2
deactivate





@enduml