# Generated by Django 2.2.2 on 2022-01-18 03:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='item_code',
            field=models.ForeignKey(db_column='item_code', limit_choices_to={'item_status': 1}, on_delete=django.db.models.deletion.CASCADE, to='itemmas.ItemInfo', verbose_name='商品コード'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reserve_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='予約日時'),
        ),
    ]
