@startuml robustness

left to right direction

usecase "TODOを登録する" as Toto

' Actors
actor "ユーザー" as User

' Boundaries
boundary "TODO登録画面" as TodoCreationScreen
boundary "登録完了画面" as CreationCompletedScreen
boundary "エラー画面" as ErrorScreen

' Controls
control "TODO登録画面を表示する" as ShowTodoCreationScreen
control "やること、期限を入力する" as InputParameters
control "入力値を検証する" as ValidateParameters
control "TODOを登録する" as CreateTodo
control "登録完了画面を表示する" as ShowCreationCompletedScreen
control "エラー画面を表示する" as ShowErrorScreen

' Entities
entity "TODO" as Todo

' ShowTodoCreationScreen -up- User  
User -[hidden]- Toto
ShowTodoCreationScreen --> TodoCreationScreen

' MainFlow
' ShowTodoCreationScreen -> TodoCreationScreen
TodoCreationScreen - InputParameters
InputParameters -> ValidateParameters : 登録ボタンを押す
ValidateParameters -> CreateTodo
CreateTodo -> ShowCreationCompletedScreen
ShowCreationCompletedScreen -> CreationCompletedScreen

' AltFlow
ValidateParameters -> ShowErrorScreen : 入力値に不備がある場合
ShowErrorScreen -> ErrorScreen

' Actor - Boundary
User - TodoCreationScreen
User - CreationCompletedScreen
User - ErrorScreen

' Control - Entity
CreateTodo - Todo

@enduml