@startuml robustness

' left to right direction

' ユースケース名 (1つのみ)
usecase "" as 

' Actors actor "" as
actor "" as

' Boundaries boundary "" as 
boundary "" as 

' Controls control "" as 
control "" as 

' Entities entity "" as
entity "" as

' Package 見やすくするのに使用してください
' package ""{
' }

' -- と - を使い分ける
' - で結んだものを近くに、横並びに表示しようとしてくれる
' -- で結んだものはいい感じに配置しようとしてくれる

' 関連の向き
' A -left- B
' A -up- C
' A -right- D
' A -down- E


' together togetherブロック内で宣言された要素は近くに配置されます。
' together {
'     class A
'     class D
' }

' hidden レイアウトのためのヒントを与える
' B -[hidden]- E

@enduml