# Generated by Django 2.2.2 on 2022-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220119_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.SmallIntegerField(choices=[(0, '管理者'), (1, '店長'), (2, '正規社員'), (3, '非正規社員')], default=3, verbose_name='雇用形態'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男性'), (1, '女性')], default=None, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='名称未設定', max_length=30, verbose_name='氏名'),
        ),
    ]
