# Generated by Django 2.2.2 on 2021-11-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aaaaa',
            fields=[
                ('id', models.AutoField(db_column='bottleneck_id', editable=False, primary_key=True, serialize=False, verbose_name='ボトルネックID')),
                ('name', models.CharField(max_length=60, verbose_name='CPU名')),
                ('balance', models.SmallIntegerField(choices=[(0, '-'), (1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], verbose_name='バランス')),
                ('wqhd', models.SmallIntegerField(choices=[(0, '-'), (1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], verbose_name='WQHD')),
                ('four_k', models.SmallIntegerField(choices=[(0, '-'), (1, '✕'), (2, '△'), (3, '〇'), (4, '◎')], verbose_name='4K解像度')),
            ],
            options={
                'verbose_name_plural': 'ボトルネックモデル',
            },
        ),
    ]
