# Generated by Django 2.2.2 on 2022-01-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='invalid_flg',
            field=models.BooleanField(default=0, verbose_name='有効'),
        ),
    ]
