# Generated by Django 2.2.2 on 2022-02-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setitems',
            name='counter',
            field=models.SmallIntegerField(default=0),
        ),
    ]
