# Generated by Django 2.2.2 on 2022-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20220119_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reserver_tel',
            field=models.CharField(max_length=14, verbose_name='連絡先'),
        ),
    ]
