# Generated by Django 2.2.2 on 2022-02-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20220204_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='invalid_flg',
            field=models.BooleanField(default=0, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', limit_choices_to={'place_category': 1}, on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗ID'),
        ),
    ]
