# Generated by Django 2.2.2 on 2022-02-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setitem',
            options={'verbose_name_plural': 'セット商品'},
        ),
    ]
