@startuml images/人事情報管理/従業員参照
' ヘッダー
header 営業情報管理システム
' タイトル
title 人事情報管理/従業員参照
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "従業員参照" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "参照" #98fb98
    class "詳細" #98fb98
    class "従業員情報" #F5A9BC
    class "店舗情報"
    class "勤務店舗状況"
}
    package "マスタ管理"{
    }
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- 詳細
    ユーザ -- ログイン
    参照 -- 従業員情報
    詳細 -- 従業員情報
    従業員情報 -- 勤務店舗状況
    従業員情報 -- マスタ管理
    従業員情報 -- 店舗情報

    'ドメインクラスの属性
    従業員情報 : 従業員ID
    従業員情報 : 氏名
    従業員情報 : 住所
    従業員情報 : 電話番号
    従業員情報 : 性別
    従業員情報 : 年齢
    従業員情報 : 生年月日
    従業員情報 : 主な店舗
    ' 店舗情報 : 店舗名
    ' 店舗情報 : 住所
    ' 店舗情報 : 連絡先
    ' 店舗情報 : 店長
    ' 店舗情報 : 主な従業員
    ' 勤務店舗状況 : 店舗名
    ' 勤務店舗状況 : 従業員数
    ' 勤務店舗状況 : 責任者
    ログイン : 従業員ID
    ログイン : パスワード




@enduml