@startuml images/人事情報管理/店舗参照
' ヘッダー
header 営業情報管理システム
' タイトル
title 人事情報管理/店舗参照
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
    class "権限編集"
}

package "店舗参照" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "参照" #98fb98
    class "詳細" #98fb98
    class "店舗情報モデル" #F5A9BC
    class "勤務店舗状況"
}
    package "マスタ管理"{
    }
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ --> 参照
    ユーザ --> 詳細 : > has-one
    ユーザ --> ログイン
    参照 --o 店舗情報モデル
    詳細 --o 店舗情報モデル : > has-many
    店舗情報モデル o-- 勤務店舗状況
    店舗情報モデル o-- マスタ管理

    'ドメインクラスの属性
    店舗情報モデル : 店舗ID
    店舗情報モデル : 場所カテゴリ
    店舗情報モデル : 店舗名
    店舗情報モデル : 住所
    店舗情報モデル : 連絡先
    店舗情報モデル : 無効フラグ
    店舗情報モデル : 作成日時
    店舗情報モデル : 最終更新日時

    ' 勤務店舗状況 : 店舗名
    ' 勤務店舗状況 : 従業員数
    ' 勤務店舗状況 : 責任者
    ログイン : 従業員ID
    ログイン : パスワード




@enduml