' ToDo
' 中間テーブルを作成して従業員情報モデルと
' 店舗情報モデルの多対多の関係を勤務状況編集の
' 中間テーブルで結ぶと良いかもしれません



@startuml ../images/人事情報管理/勤務状況編集
' ヘッダー
header 営業情報管理システム
' タイトル
title 人事情報管理/勤務状況編集
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6

}

package "勤務状況編集" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "参照" #98fb98
    class "店舗情報モデル" 
    class "従業員情報モデル" #F5A9BC
}

    'モデル同士の関係
    ユーザ --> 参照
    ユーザ --> ログイン
    参照 --o 従業員情報モデル : > has-many
    従業員情報モデル o-- 店舗情報モデル
    'ドメインクラスの属性
    従業員情報モデル : 従業員ID
    従業員情報モデル : 店舗ID[FK]
    従業員情報モデル : 雇用形態
    従業員情報モデル : 氏名
    従業員情報モデル : カナ氏名
    従業員情報モデル : 電話番号
    従業員情報モデル : 性別
    従業員情報モデル : 生年月日
    従業員情報モデル : 無効フラグ
    従業員情報モデル : 作成日時
    従業員情報モデル : 最終ログイン日時
    従業員情報モデル : 最終更新日時
    店舗情報モデル : 店舗名

    ログイン : 従業員ID
    ログイン : パスワード





@enduml