@startuml images/人事情報管理/勤務状況編集
' ヘッダー
header 営業情報管理システム
' タイトル
title 人事情報管理/勤務状況編集
' 
hide circle
' 
hide method
left to right direction

package "アカウント"{
    class "ログイン" #A9C6F6
}

package "勤務状況編集" {
    'ユーザや外部システム
    mix_actor "ユーザ"
    class "参照" #98fb98
    class "勤務店舗状況" #F5A9BC
    class "店舗情報"
}
    package "マスタ管理"{
    }
    ' class "" #F5A9BC
    ' class "" #ffd700

    'モデル同士の関係
    ユーザ -- 参照
    ユーザ -- ログイン
    参照 -- 勤務店舗状況
    勤務店舗状況 -- 店舗情報
    勤務店舗状況 -- マスタ管理

    'ドメインクラスの属性
    




@enduml