# Generated by Django 2.2.2 on 2022-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmas', '0006_auto_20220119_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='item_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '販売中'), (1, '販売済み'), (2, '修理中'), (3, '取置'), (4, '削除')], default=0, verbose_name='商品状態'),
        ),
    ]
