@startuml ../../images/売上/売上情報管理_登録
' 下アイコン除去
hide footbox
' ヘッダー
header 営業情報管理システム/人事情報管理
' タイトル
title 従業員情報管理_参照


' アイコン
actor "管理者\n正規社員" as Act
boundary "ログイン済み\nホーム画面" as HomeSc
boundary "従業員情報\n一覧画面" as StaffListSc
boundary "詳細画面" as StaffSc
control "従業員情報を取得する" as StaffCl
control "表示する" as ScCl
entity "従業員情報" as StaffDB



' ログイン済みホーム画面から一覧表示までのシーケンス
activate Act
Act -> HomeSc : 「従業員情報」を押下する
activate HomeSc
HomeSc -> StaffCl : 従業員情報一覧画面\nを要求する
deactivate
activate StaffCl

StaffCl -> StaffDB : 従業員のデータを要求する
activate StaffDB
StaffCl <-- StaffDB : 従業員のデータを返す
deactivate
StaffListSc <-- StaffCl : 一覧画面を組み立てる
deactivate
activate StaffListSc
Act <-- StaffListSc : 一覧画面を表示する


' 詳細画面表示までのシーケンス
Act -> StaffListSc : 参照したいデータを選択し押下する
StaffListSc -> ScCl : 詳細画面を要求する
deactivate
activate ScCl
StaffSc <-- ScCl
deactivate
activate StaffSc
Act <-- StaffSc : 詳細画面を表示する
deactivate




@enduml