# Generated by Django 2.2.2 on 2022-02-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemmas', '0007_auto_20220203_0237'),
        ('storemas', '0003_auto_20220119_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetItems',
            fields=[
                ('id', models.AutoField(db_column='set_item_id', editable=False, primary_key=True, serialize=False, verbose_name='セット商品ID')),
                ('set_name', models.CharField(max_length=30, verbose_name='セット名')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='最終更新日時')),
                ('desktop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop', to='itemmas.ItemInfo')),
                ('hdd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdd', to='itemmas.ItemInfo')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory', to='itemmas.ItemInfo')),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='itemmas.ItemInfo')),
                ('notepc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notepc', to='itemmas.ItemInfo')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office', to='itemmas.ItemInfo')),
                ('others', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='others', to='itemmas.ItemInfo')),
                ('ssd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssd', to='itemmas.ItemInfo')),
                ('store_id', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗ID')),
            ],
            options={
                'verbose_name_plural': 'セット商品',
            },
        ),
    ]
