# Generated by Django 2.2.2 on 2022-02-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setitem', '0002_setitems_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setitems',
            name='desktop',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 1, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop', to='itemmas.ItemInfo', verbose_name='デスクトップ'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='hdd',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 4, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hdd', to='itemmas.ItemInfo', verbose_name='HDD'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='memory',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 3, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory', to='itemmas.ItemInfo', verbose_name='メモリ'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='monitor',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 2, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='itemmas.ItemInfo', verbose_name='モニター'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='notepc',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 0, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notepc', to='itemmas.ItemInfo', verbose_name='ノートPC'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='office',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 6, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office', to='itemmas.ItemInfo', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='others',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 7, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='others', to='itemmas.ItemInfo', verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='ssd',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 5, 'item_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssd', to='itemmas.ItemInfo', verbose_name='SSD'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', limit_choices_to={'place_category': 1}, on_delete=django.db.models.deletion.CASCADE, to='storemas.StoreInfo', verbose_name='店舗ID'),
        ),
    ]
