# Generated by Django 2.2.2 on 2022-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setitem', '0003_auto_20220204_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setitems',
            name='desktop',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='デスクトップ'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='hdd',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='HDD'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='memory',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='メモリ'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='monitor',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='モニター'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='notepc',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ノートPC'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='office',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='others',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='その他'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='set_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='セット名'),
        ),
        migrations.AlterField(
            model_name='setitems',
            name='ssd',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='SSD'),
        ),
    ]
