@startuml sequence

hide footbox
header 営業情報管理システム
title マスタ管理/店舗情報を編集する

' actor "" as 
actor "管理者" as a1
' boundary "" as
boundary "ログイン済\nホーム画面" as b1
boundary "店舗情報\n一覧画面" as b2
boundary "詳細画面" as b3
boundary "編集画面" as b4
' control "" as 
control "店舗情報を\n取得する" as c1
control "表示する\n" as c2
control "入力データ\n検証" as c3
control "更新する\n" as c4
' entity "" as
entity "店舗情報\n" as e1

' ' ログイン済みホーム画面から一覧表示までのシーケンス
' activate a1
a1 -> b1
' activate b1
b1 -> c1 : ｢店舗情報マスタ｣を押下する
' deactivate
' activate c1
c1 -> e1 : 店舗情報を要求する
' activate e1
e1 --> c1 : 店舗情報を返す
' deactivate e1
c1 --> b2 : 画面を組み立てる
' deactivate c1
' activate b2
b2 --> a1 : 画面を表示する

a1 -> b2 : 
b2 -> c2 : ｢編集｣を押下
' deactivate b2
' activate c2
c2 --> b3 : 画面を組み立てる
' deactivate c2
' activate b3
b3 --> a1 : 画面を表示する

a1 -> b3
b3 -> c3
' deactivate b3
' activate c3
c3 -> c4 : 入力データ
' deactivate c3
' activate c4
c4 -> e1 : 店舗情報を\n書き換える
' deactivate c4
' activate e1
e1 --> c1 : 店舗情報を返す　　　　　　　　　　　　　　　
' deactivate e1
' activate c1
c1 --> b2 : 画面を組み立てる
' deactivate c1
' activate b2
b2 --> a1


@enduml