@startuml ../../images/店舗情報マスタ/店舗情報管理_参照

' 下アイコン除去
hide footbox
' ヘッダー
header 営業情報管理システム
' タイトル
title マスタ管理/店舗情報を参照する


' actor "" as 
actor "管理者" as a1

' boundary "" as 
boundary "ログイン済み\nホーム画面" as b1
boundary "店舗情報\n一覧画面" as b2
boundary "詳細\n画面" as b3

' control "" as 
control "店舗情報一覧\nコントローラ" as c1
control "詳細\nコントローラ" as c2

' entity "" as
entity "店舗情報" as e1


' ログイン済みホーム画面から一覧表示までのシーケンス
a1 -> b1 : 「店舗情報マスタ」を押下する
activate b1
b1 -> c1 : 店舗情報一覧画面を要求する()
deactivate b1
activate c1
c1 -> e1 : 登録情報を要求する()
activate e1
c1 <-- e1 : 要求された情報を送信する
deactivate e1

' 代替フロー
opt 参照したい店舗情報がない場合
b2 <-- c1 : 画面を組み立てる
activate b2
a1 <-- b2 : メッセージを表示する
end

b2 <-- c1 : 画面を組み立てる
deactivate c1

a1 <-- b2 : 画面を表示する
a1 -> b2 : 参照したい情報を選択し押下する
b2 -> c2 : 詳細画面を要求する()
deactivate b2
activate c2
c2 -> e1 : 登録情報を\n要求する()
activate e1
c2 <-- e1 : 要求された\n情報を送信する
deactivate e1
b3 <-- c2 : 画面を組み立てる
deactivate c2
activate b3
a1 <-- b3 : 画面を表示する
deactivate b3

@enduml