@startuml ../../images/ユーザ権限マスタ/ユーザ権限編集

hide footbox
header 営業情報管理システム
title マスタ管理/ユーザの権限を編集する

' actor "" as 
actor "管理者" as a1

' boundary "" as
boundary "ログイン済\nホーム画面" as b1
boundary "権限編集画面" as b2 

' control "" as
control "権限編集画面\nコントローラ" as c4

' entity "" as
entity "権限情報" as e1

a1 -> b1:「ユーザ権限マスタ」\nを押下する
activate b1
b1 -> c4 : 画面の表示を要求する()
deactivate b1
activate c4
c4 -> e1:情報を要求する()
activate e1
e1 --> c4:情報を送信する
deactivate e1
c4 --> b2:画面を組み立てる
deactivate c4
activate b2
b2 --> a1 : 画面を表示する
a1 -> b2:従業員と権限を選択し、\n「登録」ボタンを押下する
b2 -> b2:入力内容を検証する
alt 従業員が選択されていない場合
b2 --> a1 : メッセージを表示する
else 権限が選択されていない場合
b2 --> a1 : メッセージを表示する
end
b2 -> c4:入力された情報を送る
deactivate b2
activate c4
c4 -> c4 : 入力内容を検証する
c4 -> e1:情報の更新を要求する()
activate e1
e1 --> c4 : 処理の結果を返す
deactivate e1
opt DBの処理が失敗に終わった場合
c4 --> b2 : 画面を組み立てる
activate b2
b2 --> a1 : エラーメッセージを表示する
deactivate b2
end
c4 --> b2 : 画面を組み立てる
deactivate c4
activate b2
b2 --> a1:画面を表示する
deactivate b2

@enduml