# Generated by Django 2.2.2 on 2021-12-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setitem',
            options={'verbose_name_plural': '売上情報モデル'},
        ),
    ]
