# Generated by Django 2.2.2 on 2021-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.CharField(db_column='store_id', editable=False, max_length=3, primary_key=True, serialize=False, verbose_name='店舗ID')),
                ('place_category', models.SmallIntegerField(choices=[(0, '倉庫'), (1, '店舗'), (2, 'その他')], verbose_name='場所カテゴリ')),
                ('store_name', models.CharField(max_length=40, verbose_name='店舗名')),
                ('address', models.TextField(verbose_name='住所')),
                ('tel', models.CharField(max_length=13, verbose_name='連絡先')),
                ('invalid_flg', models.BooleanField(verbose_name='無効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name_plural': '店舗情報モデル',
            },
        ),
    ]
