@startuml ER図
' left to right direction

title 営業情報管理


package "マスタ管理" as mastermana {
  package "従業員情報マスタ"{
    entity "従業員情報" as M02{
      *従業員ID
      --
      *雇用形態
      ' 0 : 管理者  1 : 正規社員  2 : 非正規社員
      *店舗ID[FK]
      *最終ログイン日時
      *氏名
      *氏名(カナ)
      *電話番号
      *性別
      *生年月日
      *年齢
      *パスワード
      *無効フラグ
      *作成日時
      *最終更新日時
    }
    ' entity "CustomUserモデル" as M03{
    '   *従業員ID[FK]
    '   --
    ' }
  }
  package "店舗情報マスタ"{
    entity "店舗情報モデル" as M04{
      *店舗ID
      --
      *場所カテゴリ
      ' 0 : 店舗  1 : 倉庫
      *住所
      *連絡先
      *店長
      *無効フラグ
      *作成日時
      *最終更新日時
    }
  }
  package "ユーザ権限マスタ"{
  }
  package "商品情報マスタ"{
    entity "商品情報モデル" as M01 {
      *商品コード
      --
      *JANコード
      *型番
      ' 在庫場所
      *店舗ID[FK]
      *カテゴリID[FK]
      *商品状態
      ' 0 : 販売中  1 : 販売済  2 : 修理中  3 : 取置
      *仕入価格
      *商品画像
      *メーカー
      *備考
      *作成日時
      *最終更新日時
    }
    entity "商品詳細モデル" as M100000{
      *商品コード
      --
      *CPU
      *RAM
      *HDD
      *SSD
      *モニタサイズ
      *モニタ解像度(縦)
      *モニタ解像度(横)
      *カメラ
      ' 0:無 1:有
      *Wi-Fi
      ' 0:無 1:有
      *光学ドライブ
      ' 0:無 1:有
      *グラフィック
      *OS
      *
    }

    entity "セット商品モデル" as M14{
      *セット商品ID
      --
      *セット名
      *商品コード[FK]
      *型番
      *店舗ID[FK]
      *商品数
      *作成日時
      *最終更新日時
      
    }
    entity "セット商品中間モデル" as M16{
      *セット中間ID
      --
      *セット商品ID[FK]
      *商品コード[FK]
      *販売価格
    }
    entity "取置商品モデル" as M07{
      *取置予約ID
      --
      *商品コード[FK]
      *型番
      *店舗ID[FK]
      *予約者氏名
      *連絡先
      *予約日時
      *最終更新日時
    }
    entity "カテゴリモデル" as M10 {
      *カテゴリID
      --
      *カテゴリ名
    }
    ' entity "商品状態モデル" as M11 {
    '   *商品状態
    '   --
    ' }
    
  }
  package "ベンチマークマスタ"{
    entity "CPUベンチマークモデル" as M08 {
      *CPU名称[型番]
      --
      *PassMark
      *コア
      *スレッド
      *TDP
      *定格クロック
      *最大クロック
      *コスパ
      *作成日時
      *最終更新日時
    }
    entity "GPUベンチマークモデル" as M09 {
      *GPU名称[型番]
      --
      *3DMark Time Spy Graphics
      *TDP
      *コスパ
      *ワットパフォーマンス
      *作成日時
      *最終更新日時
    }
  }
  package "売上情報マスタ" {
    entity "売上情報モデル" as M06{
      *売上情報ID
      --
      *商品コード[FK]
      *仕入価格
      *販売価格
      *粗利
      *粗利率
      *店舗ID[FK]
      *販売日
      *最終更新日時
      
    }
  }
}

' package "勤務店舗状況編集"{
'   entity "勤務状況モデル" as M15{
'     *従業員ID[FK]
'     --
'     *従業員名[FK]
'     *勤務店舗名[FK]
'     *勤務フラグ
'     *最終更新日時
    
'   }
' }

' ベンチマークマスタ -[hidden]up- 商品情報マスタ
' 店舗情報マスタ -[hidden]left- 商品情報マスタ


M02 }|-r-|{ M04
M08 }|--o{ M01
M09 }|--o{ M01
M16 }|--|{ M01
M16 }|--|{ M14
M01 ||-d-|{ M07
M07 }|--|| M04
M04 }|--|{ M14
M06 ||--|{ M01
M10 ||-r-|{ M01
M04 ||--|{ M01 
M14 ||-u-|{ M01 



' M08 -[hidden]down- M09

' セット一覧}|--o|セット
' セット一覧}|-r-||カテゴリ
' セット||-r-||新規
' セット||-d-||編集
' セット||-l-||詳細
' 従業員 }|-d-|| M05
' M05 ||-d-|{ ベンチマーク
' M05 ||-d-o{ セット一覧
' M05 ||-d-o{ 店舗



' セット商品情報}|-d-||倉庫情報

' 倉庫情報||-d-o{取置商品情報
' 倉庫情報||-r-{ベンチマーク情報2
' 取置商品情報||-d-||見積情報2
' 見積情報2||-d-||売上情報



' M03 ||-r-|{ 勤務店舗
' M03 ||--|{ 従業員情報2
' M03 ||-d-|{ 店舗情報2

' 店舗情報2||-d-||店舗
' ベンチマーク||-d-o{ベンチマーク情報2






' entity Meta{
'     -保留
' }

' itemmana -[hidden]- huremana
' mastermana -[hidden]down- itemmana
' mastermana -[hidden]down- huremana

' 要素の書き出しから


' CustomUser +-- Meta
@enduml
