@startuml ER図
' left to right direction

title 営業情報管理


package "マスタ管理" as mastermana {
  package "従業員情報マスタ"{
    entity "従業員情報" as M02{
      *従業員I D
      --
      *雇用形態[FK]
      *雇用店舗名[FK]
      *氏名
      *氏名(カナ)
      *電話番号
      *性別
      *生年月日
      *年齢
      *無効フラグ
    }
    entity "CustomUserモデル" as M03{
      *従業員I D[FK]
      --
      *パスワード
    }
  }
  package "店舗情報マスタ"{
    entity "店舗情報モデル" as M04{
      *店舗I D
      *店舗名
      --
      *住所
      *連絡先
      *店長
    }
  }
  package "ユーザ権限マスタ"{
    entity "権限情報" as M05{
      *雇用形態
      --
    }
  }
  package "商品情報マスタ"{
    entity "商品情報モデル" as M01 {
      *商品コード
      *JANコード
      *型番
      --
      *在庫場所[FK]
      *カテゴリ[FK]
      *商品状態[FK]
      *仕入価格
      *商品画像
    }

    entity "セット商品モデル" as M14{
      *I D
      *型番[FK]
      --
      *取扱店舗名[FK]
      *商品数
      *作成日時
      *最終更新日時
      
    }
    entity "取置商品モデル" as M07{
      *I D
      *型番[FK]
      --
      *取置店舗名[FK]
      *予約者氏名
      *連絡先
      *予約日時
      *最終更新日時
    }
    entity "カテゴリモデル" as M10 {
      *カテゴリ名
      --
    }
    entity "商品状態モデル" as M11 {
      *商品状態
      --
    }
    entity "在庫場所モデル" as M12 {
      *在庫場所名
    }

  }
  package "ベンチマークマスタ"{
    entity "CPUベンチマークモデル" as M08 {
      *I D
      *CPU名称[型番]
      --
      *PassMark
      *コア
      *スレッド
      *TDP
      *定格クロック
      *最大クロック
      *コスパ
      *作成日時
      *最終更新日時
    }
    entity "GPUベンチマークモデル" as M09 {
      *I D
      *GPU名称[型番]
      --
      *3DMark Time Spy Graphics
      *TDP
      *コスパ
      *ワットパフォーマンス
      *作成日時
      *最終更新日時
    }
  }
  package "売上情報マスタ" {
    entity "売上情報モデル" as M06{
      *I D
      *型番[FK]
      --
      *仕入価格[FK]
      *販売価格
      *粗利
      *粗利率
      *販売店舗名[FK]
      *消費税
      *消費税率[FK]
      *販売日
      *最終更新日時
      
    }
    entity "消費税率モデル" as M13 {
      *消費税率
      --
    }
  }
}

package "勤務店舗状況編集"{
  entity "勤務状況モデル" as M15{
    *従業員ID[FK]
    --
    *従業員名[FK]
    *勤務店舗名[FK]
    *勤務フラグ
    *最終更新日時
    *
    
  }
}

ベンチマークマスタ -[hidden]up- 商品情報マスタ

M02 ||--|| M03
M02 }|-r-|{ M04
M02 ||-u-|| M05
M13 ||--o{ M06
M08 }|--o{ M01
M09 }|--o{ M01
M07 -[hidden]right-M11
M11 -[hidden]right-M12
' M10 -[hidden]down- M11
' M11 -[hidden]down- M12
M06 ||--|{ M01
M10 ||-l-|{ M01
M11 ||-l-|{ M01
M12 ||-u-|{ M01 
M14 ||-r-|{ M01 
M07 ||-u-|{ M01
M15 ||--|{ M02
M15 }o--o{ M04


' M08 -[hidden]down- M09

' セット一覧}|--o|セット
' セット一覧}|-r-||カテゴリ
' セット||-r-||新規
' セット||-d-||編集
' セット||-l-||詳細
' 従業員 }|-d-|| M05
' M05 ||-d-|{ ベンチマーク
' M05 ||-d-o{ セット一覧
' M05 ||-d-o{ 店舗



' セット商品情報}|-d-||倉庫情報

' 倉庫情報||-d-o{取置商品情報
' 倉庫情報||-r-{ベンチマーク情報2
' 取置商品情報||-d-||見積情報2
' 見積情報2||-d-||売上情報



' M03 ||-r-|{ 勤務店舗
' M03 ||--|{ 従業員情報2
' M03 ||-d-|{ 店舗情報2

' 店舗情報2||-d-||店舗
' ベンチマーク||-d-o{ベンチマーク情報2






' entity Meta{
'     -保留
' }

' itemmana -[hidden]- huremana
' mastermana -[hidden]down- itemmana
' mastermana -[hidden]down- huremana

' 要素の書き出しから


' CustomUser +-- Meta
@enduml
