@startuml クラス図

title 営業情報管理

' 'ベンチマークマスタ
class ベンチマーク情報{
    ' 保留中
}
'ユーザ権限
class 権限情報{
    管理者
    正規社員
    非正規社員
}
' ログイン
class ログイン{}
' 勤務店舗状況編集
class 従業員情報{
    -従業員ID
    -権限
    -氏名
    -住所
    -電話番号
    -性別
    -年齢
    -生年月日
    -店舗
}
class 店舗情報{
    -店舗名
    -住所
    -連絡先
    -店長
    -主な従業員
}
class 店舗名{
    -店舗A
    -店舗B
    -店舗C
    -店舗D
}

class 商品情報{
    -型番
    -商品コード
    -JANコード
    -商品画像
    -在庫場所
    -カテゴリ
    -仕入価格
}
class 売上情報{}
class セット商品情報{
    -販売価格
    ' 保留中
}
class 取置商品情報{}
class カテゴリ{
    -ノートPC
    -デスクトップPC
    -モニター
    -メモリ
    -HDD
    -SSD
}
class 倉庫情報{
    -倉庫名
    -
    +移動指示()
}
class CustomUser{
    -従業員ID
    -パスワード
}
class Meta{
    -保留
}
class django-allauth {
    +ログイン()
}

CustomUser +-- Meta
@enduml
