@startuml クラス図
' left to right direction

title 営業情報管理


package "マスタ管理" as mastermana {
    package 従業員情報マスタ{
        ' 従業員情報
        ' モデル
        class 従業員情報(従業員情報){
            -従業員ID
            -権限
            -氏名
            -住所
            -電話番号
            -性別
            -年齢
            -生年月日
            -店舗
        }
    }
    package "店舗情報マスタ"{
        ' 店舗情報
        ' モデル
        class 店舗情報(店舗情報){
            -店舗名
            -住所
            -連絡先
            -店長
            -主な従業員
        }
        class 店舗名(店舗名){
            -店舗A
            -店舗B
            -店舗C
            -店舗D
        }
    }
    package ユーザ権限マスタ{
        'ユーザ権限'
        ' モデル
        class 権限情報(権限情報){
            管理者
            正規社員
            非正規社員
        }
    }
    package 商品情報マスタ{
        ' 商品情報管理
        ' モデル
        class セット商品情報(セット商品情報){
            -販売価格
            ' 保留中
        }
        class カテゴリ(カテゴリ){
            -ノートPC
            -デスクトップPC
            -モニター
            -メモリ
            -HDD
            -SSD
        }
        ' コントローラ
        ' class セット商品情報一覧(商品情報一覧){}
        ' class 新規登録(新規登録)){}
        ' class 詳細(詳細){}
        ' class 編集(編集){}
    }
    package ベンチマークマスタ{
        ' ベンチマークマスタ
        ' モデル
        class ベンチマーク情報(ベンチマーク情報){
            ' 保留中
        }
    }
    ' package 売上情報マスタ{
        ' 売上情報
        ' モデル
        
}


package "商品情報管理" as itemmana {
    package 在庫管理{
        ' 商品情報管理
        ' モデル
        class セット商品情報(セット商品情報){
            -販売価格
            ' 保留中
        }
        class 倉庫情報(倉庫情報){
        -倉庫名
        ' +移動指示()
        }
    }
    package 検索機能{
        ' ベンチマークマスタ
        ' モデル
        class ベンチマーク情報2(ベンチマーク情報2){
            ' 保留中
            -空で大丈夫
        }
    }
    package 取置予約管理(取置予約管理){
        ' 取置商品情報
        ' モデル
        class 取置商品情報(取置商品情報){}
    }
    package 見積{
        class 見積情報2(見積情報2){
            -空で大丈夫
        }
    }
    package 売上{
        ' 売上情報
        ' モデル
        class 売上情報(売上情報){}
    }
    
    
}


package "人事情報管理" as huremana {
    package 従業員情報参照{
        class 従業員情報2(従業員情報2){
            -空で大丈夫
        }
    }
    package 店舗情報参照{
        class 店舗情報2(店舗情報2){
            -空で大丈夫
        }
    }
    package 勤務店舗状況編集{
        class 勤務店舗状況(勤務店舗状況){
            -従業員ID
            -権限
            -氏名
            -住所
            -電話番号
            -店舗
        }
    }
    package ログイン{
        ' ログイン'
        ' モデル
        ' class "django-allauth(ログイン)" as da{
        '     -従業員ID
        '     -パスワード
        '     ' +ログイン()
        ' }
        class CustomUser(ログイン){
            -従業員ID
            -パスワード
        }
    }
}



' class Meta{
'     -保留
' }

mastermana -[hidden]down- itemmana
itemmana -[hidden]down- huremana
' itemmana -[hidden]- huremana
' mastermana -[hidden]down- itemmana
' mastermana -[hidden]down- huremana

' 要素の書き出しから


' CustomUser +-- Meta
@enduml
