@startuml クラス図
' left to right direction

title 営業情報管理


package "マスタ管理" as mastermana {
    package 従業員情報マスタ{
        ' 従業員情報
        ' モデル
        entity "従業員情報(従業員情報)" as 従業員{
            -従業員ID
            -権限
            -氏名
            -住所
            -電話番号
            -性別
            -年齢
            -生年月日
            -店舗
        }
    }
    package "店舗情報マスタ"{
        ' 店舗情報
        ' モデル
        entity "店舗情報(店舗情報)" as 店舗{
            -店舗名
            -住所
            -連絡先
            -店長
            -主な従業員
        }
        entity "店舗名(店舗名)" as 店舗名{
            -店舗A
            -店舗B
            -店舗C
            -店舗D
        }
    }
    package ユーザ権限マスタ{
        'ユーザ権限'
        ' モデル
        entity "権限情報(権限情報)" as 権限{
            管理者
            正規社員
            非正規社員
        }
    }
    package 商品情報マスタ{
        ' 商品情報管理
        ' モデル
        entity "セット商品情報(セット商品情報)" as セット{
            -販売価格
            ' 保留中
        }
        entity "カテゴリ(カテゴリ)" as カテゴリ{
            -ノートPC
            -デスクトップPC
            -モニター
            -メモリ
            -HDD
            -SSD
        }
        ' コントローラ
        entity セット商品情報一覧(商品情報一覧){}
        entity 新規登録(新規登録)){}
        entity 詳細(詳細){}
        entity 編集(編集){}
    }
    package ベンチマークマスタ{
        ' ベンチマークマスタ
        ' モデル
        entity "ベンチマーク情報(ベンチマーク情報)" as ベンチマーク{
            ' 保留中
        }
    }
    ' package 売上情報マスタ{
        ' 売上情報
        ' モデル
        従業員 ||-d-o{ 権限
        権限 ||-d-o{ ベンチマーク
        権限 ||-d-o{ セット
        権限 ||-d-o{ 店舗

}


package "商品情報管理" as itemmana {
    package 在庫管理{
        ' 商品情報管理
        ' モデル
        entity "セット商品情報(セット商品情報)" as セット商品情報{
            -販売価格
            ' 保留中
        }
        entity "倉庫情報(倉庫情報)" as 倉庫情報{
        -倉庫名
        ' +移動指示()
        }
    }
    package 検索機能{
        ' ベンチマークマスタ
        ' モデル
        entity "ベンチマーク情報2(ベンチマーク情報2)" as ベンチマーク情報2{
            ' 保留中
            -空で大丈夫
        }
    }
    package 取置予約管理(取置予約管理){
        ' 取置商品情報
        ' モデル
        entity "取置商品情報(取置商品情報)" as 取置商品情報{

        }
    }
    package 見積{
        entity "見積情報2(見積情報2)" as 見積情報2{
            -空で大丈夫
        }
    }
    package 売上{
        ' 売上情報
        ' モデル
        entity "売上情報(売上情報)" as 売上情報{}
    }
    倉庫情報||-d-o{取置商品情報
    倉庫情報||--o{ベンチマーク情報2
    取置商品情報||-d-o{見積情報2
    見積情報2||-d-o{売上情報

    
}


package "人事情報管理" as huremana {
    package 従業員情報参照{
        entity "従業員情報2(従業員情報2)" as 従業員情報2{
            -空で大丈夫
        }
    }
    package 店舗情報参照{
        entity "店舗情報2(店舗情報2)" as 店舗情報2{}
    }
    package 勤務店舗状況編集{
        entity "勤務店舗状況(勤務店舗状況)" as 勤務店舗{
            -従業員ID
            -権限
            -氏名
            -住所
            -電話番号
            -店舗
        }
    }
    package ログイン{
        ' ログイン'
        ' モデル
        ' entity "django-allauth(ログイン)" as da{
        '     -従業員ID
        '     -パスワード
        '     ' +ログイン()
        ' }
        entity "CustomUser(ログイン)" as login{
            -従業員ID
            -パスワード
        }
    }
    login ||-r-o{ 勤務店舗
    login ||--o{ 従業員情報2
    login ||-d-o{ 店舗情報2
}


店舗情報2||-d-o{店舗
ベンチマーク||-d-o{ベンチマーク情報2






' entity Meta{
'     -保留
' }

' itemmana -[hidden]- huremana
' mastermana -[hidden]down- itemmana
' mastermana -[hidden]down- huremana

' 要素の書き出しから


' CustomUser +-- Meta
@enduml
